// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package mono

import (
	"errors"
	"fmt"
)

const (
	// DataSyncCodeSYNCEDSUCCESSFUL is a DataSyncCode of type SYNCED_SUCCESSFUL.
	DataSyncCodeSYNCEDSUCCESSFUL DataSyncCode = "SYNCED_SUCCESSFUL"
	// DataSyncCodeSYNCSUCCESSFUL is a DataSyncCode of type SYNC_SUCCESSFUL.
	DataSyncCodeSYNCSUCCESSFUL DataSyncCode = "SYNC_SUCCESSFUL"
	// DataSyncCodeREAUTHORISATIONREQUIRED is a DataSyncCode of type REAUTHORISATION_REQUIRED.
	DataSyncCodeREAUTHORISATIONREQUIRED DataSyncCode = "REAUTHORISATION_REQUIRED"
	// DataSyncCodeINCOMPLETESTATEMENTERROR is a DataSyncCode of type INCOMPLETE_STATEMENT_ERROR.
	DataSyncCodeINCOMPLETESTATEMENTERROR DataSyncCode = "INCOMPLETE_STATEMENT_ERROR"
)

var ErrInvalidDataSyncCode = errors.New("not a valid DataSyncCode")

// String implements the Stringer interface.
func (x DataSyncCode) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DataSyncCode) IsValid() bool {
	_, err := ParseDataSyncCode(string(x))
	return err == nil
}

var _DataSyncCodeValue = map[string]DataSyncCode{
	"SYNCED_SUCCESSFUL":          DataSyncCodeSYNCEDSUCCESSFUL,
	"SYNC_SUCCESSFUL":            DataSyncCodeSYNCSUCCESSFUL,
	"REAUTHORISATION_REQUIRED":   DataSyncCodeREAUTHORISATIONREQUIRED,
	"INCOMPLETE_STATEMENT_ERROR": DataSyncCodeINCOMPLETESTATEMENTERROR,
}

// ParseDataSyncCode attempts to convert a string to a DataSyncCode.
func ParseDataSyncCode(name string) (DataSyncCode, error) {
	if x, ok := _DataSyncCodeValue[name]; ok {
		return x, nil
	}
	return DataSyncCode(""), fmt.Errorf("%s is %w", name, ErrInvalidDataSyncCode)
}
