// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package mono

import (
	"errors"
	"fmt"
)

const (
	// ReauthorisationRequestScopeReauth is a ReauthorisationRequestScope of type reauth.
	ReauthorisationRequestScopeReauth ReauthorisationRequestScope = "reauth"
)

var ErrInvalidReauthorisationRequestScope = errors.New("not a valid ReauthorisationRequestScope")

// String implements the Stringer interface.
func (x ReauthorisationRequestScope) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ReauthorisationRequestScope) IsValid() bool {
	_, err := ParseReauthorisationRequestScope(string(x))
	return err == nil
}

var _ReauthorisationRequestScopeValue = map[string]ReauthorisationRequestScope{
	"reauth": ReauthorisationRequestScopeReauth,
}

// ParseReauthorisationRequestScope attempts to convert a string to a ReauthorisationRequestScope.
func ParseReauthorisationRequestScope(name string) (ReauthorisationRequestScope, error) {
	if x, ok := _ReauthorisationRequestScopeValue[name]; ok {
		return x, nil
	}
	return ReauthorisationRequestScope(""), fmt.Errorf("%s is %w", name, ErrInvalidReauthorisationRequestScope)
}
