// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package mono

import (
	"errors"
	"fmt"
)

const (
	// CustomerTypeIndividual is a CustomerType of type individual.
	CustomerTypeIndividual CustomerType = "individual"
	// CustomerTypeBusiness is a CustomerType of type business.
	CustomerTypeBusiness CustomerType = "business"
)

var ErrInvalidCustomerType = errors.New("not a valid CustomerType")

// String implements the Stringer interface.
func (x CustomerType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x CustomerType) IsValid() bool {
	_, err := ParseCustomerType(string(x))
	return err == nil
}

var _CustomerTypeValue = map[string]CustomerType{
	"individual": CustomerTypeIndividual,
	"business":   CustomerTypeBusiness,
}

// ParseCustomerType attempts to convert a string to a CustomerType.
func ParseCustomerType(name string) (CustomerType, error) {
	if x, ok := _CustomerTypeValue[name]; ok {
		return x, nil
	}
	return CustomerType(""), fmt.Errorf("%s is %w", name, ErrInvalidCustomerType)
}
