// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package mono

import (
	"errors"
	"fmt"
)

const (
	// DebitTypeFixed is a DebitType of type fixed.
	DebitTypeFixed DebitType = "fixed"
	// DebitTypeVariable is a DebitType of type variable.
	DebitTypeVariable DebitType = "variable"
)

var ErrInvalidDebitType = errors.New("not a valid DebitType")

// String implements the Stringer interface.
func (x DebitType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DebitType) IsValid() bool {
	_, err := ParseDebitType(string(x))
	return err == nil
}

var _DebitTypeValue = map[string]DebitType{
	"fixed":    DebitTypeFixed,
	"variable": DebitTypeVariable,
}

// ParseDebitType attempts to convert a string to a DebitType.
func ParseDebitType(name string) (DebitType, error) {
	if x, ok := _DebitTypeValue[name]; ok {
		return x, nil
	}
	return DebitType(""), fmt.Errorf("%s is %w", name, ErrInvalidDebitType)
}

const (
	// DirectDebitPaymentScheduleTypeRecurringDebit is a DirectDebitPaymentScheduleType of type recurring-debit.
	DirectDebitPaymentScheduleTypeRecurringDebit DirectDebitPaymentScheduleType = "recurring-debit"
	// DirectDebitPaymentScheduleTypeOneTime is a DirectDebitPaymentScheduleType of type one-time.
	DirectDebitPaymentScheduleTypeOneTime DirectDebitPaymentScheduleType = "one-time"
)

var ErrInvalidDirectDebitPaymentScheduleType = errors.New("not a valid DirectDebitPaymentScheduleType")

// String implements the Stringer interface.
func (x DirectDebitPaymentScheduleType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DirectDebitPaymentScheduleType) IsValid() bool {
	_, err := ParseDirectDebitPaymentScheduleType(string(x))
	return err == nil
}

var _DirectDebitPaymentScheduleTypeValue = map[string]DirectDebitPaymentScheduleType{
	"recurring-debit": DirectDebitPaymentScheduleTypeRecurringDebit,
	"one-time":        DirectDebitPaymentScheduleTypeOneTime,
}

// ParseDirectDebitPaymentScheduleType attempts to convert a string to a DirectDebitPaymentScheduleType.
func ParseDirectDebitPaymentScheduleType(name string) (DirectDebitPaymentScheduleType, error) {
	if x, ok := _DirectDebitPaymentScheduleTypeValue[name]; ok {
		return x, nil
	}
	return DirectDebitPaymentScheduleType(""), fmt.Errorf("%s is %w", name, ErrInvalidDirectDebitPaymentScheduleType)
}

const (
	// DirectPayMethodMandate is a DirectPayMethod of type mandate.
	DirectPayMethodMandate DirectPayMethod = "mandate"
)

var ErrInvalidDirectPayMethod = errors.New("not a valid DirectPayMethod")

// String implements the Stringer interface.
func (x DirectPayMethod) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DirectPayMethod) IsValid() bool {
	_, err := ParseDirectPayMethod(string(x))
	return err == nil
}

var _DirectPayMethodValue = map[string]DirectPayMethod{
	"mandate": DirectPayMethodMandate,
}

// ParseDirectPayMethod attempts to convert a string to a DirectPayMethod.
func ParseDirectPayMethod(name string) (DirectPayMethod, error) {
	if x, ok := _DirectPayMethodValue[name]; ok {
		return x, nil
	}
	return DirectPayMethod(""), fmt.Errorf("%s is %w", name, ErrInvalidDirectPayMethod)
}

const (
	// MandateTypeEmandate is a MandateType of type emandate.
	MandateTypeEmandate MandateType = "emandate"
	// MandateTypeGsm is a MandateType of type gsm.
	MandateTypeGsm MandateType = "gsm"
	// MandateTypeSigned is a MandateType of type signed.
	MandateTypeSigned MandateType = "signed"
)

var ErrInvalidMandateType = errors.New("not a valid MandateType")

// String implements the Stringer interface.
func (x MandateType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x MandateType) IsValid() bool {
	_, err := ParseMandateType(string(x))
	return err == nil
}

var _MandateTypeValue = map[string]MandateType{
	"emandate": MandateTypeEmandate,
	"gsm":      MandateTypeGsm,
	"signed":   MandateTypeSigned,
}

// ParseMandateType attempts to convert a string to a MandateType.
func ParseMandateType(name string) (MandateType, error) {
	if x, ok := _MandateTypeValue[name]; ok {
		return x, nil
	}
	return MandateType(""), fmt.Errorf("%s is %w", name, ErrInvalidMandateType)
}
