// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package mono

import (
	"errors"
	"fmt"
)

const (
	// MandateTypeEmandata is a MandateType of type emandata.
	MandateTypeEmandata MandateType = "emandata"
	// MandateTypeGsm is a MandateType of type gsm.
	MandateTypeGsm MandateType = "gsm"
	// MandateTypeSigned is a MandateType of type signed.
	MandateTypeSigned MandateType = "signed"
)

var ErrInvalidMandateType = errors.New("not a valid MandateType")

// String implements the Stringer interface.
func (x MandateType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x MandateType) IsValid() bool {
	_, err := ParseMandateType(string(x))
	return err == nil
}

var _MandateTypeValue = map[string]MandateType{
	"emandata": MandateTypeEmandata,
	"gsm":      MandateTypeGsm,
	"signed":   MandateTypeSigned,
}

// ParseMandateType attempts to convert a string to a MandateType.
func ParseMandateType(name string) (MandateType, error) {
	if x, ok := _MandateTypeValue[name]; ok {
		return x, nil
	}
	return MandateType(""), fmt.Errorf("%s is %w", name, ErrInvalidMandateType)
}
